//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiSampleApp
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Contact
    {
        public int ContactID { get; set; }
        [DisplayName("First Name")]
        [Required]
        public string ContactPersonFname { get; set; }
        [DisplayName("Last Name")]
        [Required]
        public string ContactPersonLname { get; set; }
        [DisplayName("Mobile Phone No")]
        [Required]
        public string ContactNo1 { get; set; }
        [DisplayName("Work Phone No")]
        [Required]
        public string ContactNo2 { get; set; }
        [Required]
        public string EmailID { get; set; }
        public int CountryID { get; set; }
        public int StateID { get; set; }
        [Required]
        public string Address { get; set; }
        public string ImagePath { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual State State { get; set; }
    }
}
